// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ranhcnsaxkbgsckrqyxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhbmhjbnNheGtiZ3Nja3JxeXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5NTEzNTMsImV4cCI6MjA3NTUyNzM1M30.sNhKtBiC5ddKUH9PLbq56GorgNOCHJR4IOAWO02htaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);