// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://esckspxnezngxhnqmznc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzY2tzcHhuZXpuZ3hobnFtem5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNjIyNTUsImV4cCI6MjA3NjczODI1NX0.zwUUm_1ZJtV9Qy9AiCOI-vQKga43pRIGJG5nURGboN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);